### ISSUE TITLE
Rectangle border of objects

### ISSUE THREAD

**Issue by plastic-kai** [hanuor/onyx#1]
It will help a lot if user be able to know the location of the objects.
BTW, AWSOME project! love it.

**Comment by ghost** [comment]
Hi Kai,
I just wanted to clarify, do you want to fetch the location pixel wise of each and every object that is being scanned?

**Comment by plastic-kai** [comment]
Hi Shanjohri,
I think large, obvious objects are good enough. For example, in the example image, we found snow, wolf, mammal. Snow is small and everywhere, maybe just wolf is OK?

This function will be quit useful, e.g. you can track a dog with camera :)

The expected effect is kind of like Fei Fei Li's introduction to computer vision, at about 18min:
https://www.youtube.com/watch?v=ylVsqXzlJqA

**Comment by ghost** [comment]
Yeah that's a good question. Maybe you can **filter out** the results depending on their probabilities of occurring. For example if you use .getTagsandProbability() method then what you'll get in response is going to an arraylist of the tags as well as their probability of occurring.
 You can checkout the sample app code to understand this more practically. So in the image where there are two wolves, we mostly see the color white(the fur) and some snow in the backdrop. The probability of snow occurring in the picture hence is larger (0.9974 approx.) whereas the second highest probability is of the tag 'wolf' ( 0.996 approx). Thus, it depends on what and how much part a group of pixels are depicting in an image.
And yes, we are striving to add that feature too. We are looking forward to implement scanning of objects in a video. So in-fact you can surely imitate what Fei Fei is showing you in the video :)
I do hope this answers your query. Please do hit me back if not. And yeah, thank you for your kind words, this motivates us implement more and more. :)
Also you can checkout [https://www.youtube.com/watch?v=n6hpQwq7Inw](this) video if you want to know the technology behind the scanning of images.
Edit: Good news :) we've updated the library. Checkout the new feature yourself :100:  :)
